purchase/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'purchase' 

urlpatterns = [
    url(r'^index/$',views.IndexView.as_view(),name='index'),
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    #url(r'^login/$',login,{'template_name':'purchase/login.html'},name='login'),
    url(r'^login/$',views.UserLoginView.as_view(),name='login'),
    #url(r'^logout/$',logout,{'next_page':'/index'},name='logout'),
    url(r'^logout/$',views.UserLogoutView.as_view(),name='logout'),
   # url(r'^user/(?P<pk>[0-9]+)/$',login_required(views.UserView.as_view(),login_url='purchase:login'),name='user'),
    url(r'^item/$',views.ItemView.as_view(),name='item'),
    url(r'^item/(?P<pk>[0-9]+)/details/$',views.DetailView.as_view(),name='details'),
    url(r'^item/(?P<pk>[0-9]+)/add/$',views.AddToCart.as_view(),name='add'),
    url(r'^item/(?P<pk>[0-9]+)/like/$',views.AddToLike.as_view(),name='like'),
    url(r'^item/(?P<pk>[0-9]+)/favorite/$',views.AddToFavorite.as_view(),name='favorite'),
    url(r'^user/cart/$',views.CartDetailsView.as_view(),name='cartdetails'),
    url(r'^user/cart/order/$',views.PlaceOrder.as_view(),name='order'),
    url(r'^user/cart/(?P<pk>[0-9]+)/delete/$',views.DeleteItem.as_view(),name='deleteitem'),
    url(r'^user/cart/empty/$',views.EmptyCart.as_view(),name='emptycart'),
    url(r'^user/cart/order/orderdetails$',views.OrderDetails.as_view(),name='orderdetails'),
    url(r'^user/profile/$',views.UserProfileView.as_view(),name='userprofile'),
    url(r'^user/setting/$',views.UserSettingView.as_view(),name='usersetting'),
]

smart_shop/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('purchase.urls')),
    
]

purchase/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Userdetails(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    profilepic = models.CharField(max_length=200,default='../../static/purchase/images/')
    address = models.CharField(max_length=2000)
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return  self.customer.username + " has number " + str(self.phone_number)
    


class Category(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category

class Item(models.Model):

    name = models.CharField(max_length=100)
    details = models.CharField(max_length=1000)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()
    logo = models.CharField(max_length=500,default='../../static/purchase/images/')

    def __str__(self):
        return self.name

class Cart(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Item,on_delete=models.CASCADE)
    add_date = models.DateTimeField(default=timezone.now())
 
    def __str__(self):
        return self.customer.username + ' - ' + self.product.name

class Favorite(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Item,on_delete=models.CASCADE)
    add_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.customer.username + ' * ' + self.product.name 

class Like(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Item,on_delete=models.CASCADE)
    add_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.customer.username + ' liked ' + self.product.name


class Order(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Cart,on_delete=models.CASCADE)
    order_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.customer.username + ' ordered ' + self.product.product.category.category

purchase/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ['username','email','password']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

class UserDetailsForm(forms.Form):
	address = forms.CharField(max_length=2000)
	phone_number = forms.CharField(max_length=20)

purchase/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views import generic
from .forms import *
from django.shortcuts import render,redirect
from django.http import HttpResponseNotModified
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth import login,logout
from .models import *


class IndexView(generic.ListView):

    template_name = 'purchase/index.html'
    context_object_name = 'items'

    def get_queryset(self):
        return Item.objects.all()


class UserLoginView(generic.View):
    template_name = 'purchase/login.html'
    form_class = LoginForm
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('purchase:index')
        return render(request,self.template_name,{'form':form})

class UserLogoutView(generic.View):
    def get(self,request):
        logout(request)
        return redirect('purchase:index')


class UserProfileView(generic.View):

    template_name = 'purchase/userprofile.html'

    def get(self,request):
        user = User.objects.get(username=request.user.username)
        details = user.userdetails_set.all()
        return render(request,'purchase/userprofile.html',{'details':details})


class UserSettingView(generic.TemplateView):

    template_name = 'purchase/usersetting.html'


class UserFormView(generic.View):
    form_class = UserForm
    template_name = 'purchase/register.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username = username,password=password)

            if user is not None:
                
                login(request,user)
                return redirect('purchase:index')

        
        return render(request,self.template_name,{'form':form})


class ItemView(generic.ListView):

    template_name = 'purchase/item.html'
    context_object_name = 'category'

    def get_queryset(self):
        x1 = Category.objects.get(id=1)
        x3 = Category.objects.get(id=3)
        x8 = Category.objects.get(id=8)
        x={'x1':x1,'x3':x3,'x8':x8}
        return x

class DetailView(generic.DetailView):
    model = Item
    context_object_name = "item"
    template_name = 'purchase/details.html'

class CartDetailsView(generic.TemplateView):
    template_name = 'purchase/cartdetails.html'


class AddToCart(generic.View):

    template_name = 'purchase/item.html'

    def get(self,request,**kwargs):
        item = Item.objects.get(id=self.kwargs['pk'])
        name = User.objects.get(username=request.user.username)
        c = Cart(customer=name,product=item)
        c.save()
        return redirect('purchase:item')


class AddToFavorite(generic.View):

    template_name = 'purchase/item.html'

    def get(self,request,**kwargs):
        item = Item.objects.get(id=self.kwargs['pk'])
        name = User.objects.get(username=request.user.username)
        f = Favorite(customer=name,product=item)
        f.save()
        return redirect('purchase:item') 


class AddToLike(generic.View):

    template_name = 'purchase/item.html'

    def get(self,request,**kwargs):
        item = Item.objects.get(id=self.kwargs['pk'])
        name = User.objects.get(username=request.user.username)
        l = Like(customer=name,product=item)
        l.save()
        return redirect('purchase:item')  

class PlaceOrder(generic.View):

    def get(self,request):
        #item = Item.objects.get(id=self.kwargs['pk'])
        name = User.objects.get(username=request.user.username)
        cart = Cart.objects.filter(customer_id=request.user.id)

        for c in cart:
            item = Cart.objects.get(id=c.id)
            o = Order(customer=name,product=item)
            o.save()

        return redirect('purchase:orderdetails')

class DeleteItem(generic.View):
    
    def get(self,request,**kwargs):
        Cart.objects.get(customer_id=request.user.id,product_id=self.kwargs['pk']).delete()
        return redirect('purchase:cartdetails')

class EmptyCart(generic.View):

    def get(self,request):
        items = Cart.objects.filter(customer_id=request.user.id)
        for item in items:
            Cart.objects.get(id=item.id).delete()

        return redirect('purchase:item')

class OrderDetails(generic.View):

    template_name = 'purchase/order.html'
    form_class = UserDetailsForm

    def get(self,request):
        cart = Order.objects.filter(customer_id=request.user.id)
        form = self.form_class
        return render(request,self.template_name,{'form':form,'cart':cart})

purchase/templates/purchase/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}SmartShop{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'purchase/css/bootstrap.css' %}"/>
    <script src="{% static 'purchase/js/jquery.js' %}"></script>
    <script src="{% static 'purchase/js/bootstrap.js' %}"></script>
    {% block script %}<script></script>{% endblock %}
    {% block style %}
    <style>
        .btn-circle {
            width: 30px;
            height: 30px;
            text-align: center;
            padding: 6px 0;
            font-size: 12px;
            line-height: 1.428571429;
            border-radius: 15px;
            display: inline-block
        }
        .bottom-rule{
				border-bottom: 1px solid lightgray;
		}

		footer{
				padding-top: 20px;
				border-top: 10px solid #332e20;
				background-color: white;
			}
		.footer-section {
			    margin-bottom: 20px;
			    padding-bottom: 20px;
			    border-bottom: 1px solid lightgray;
 			}
 		.monospaced { 
 				font-family: 'Ubuntu Mono', monospaced ; 
 			}
 		.leg-room { margin-bottom: 20px; padding-bottom: 20px; }
    </style>
    {% endblock %}
</head>
<body>


<nav class="navbar navbar-inverse">

    <div class="containe-fluid">
        
        
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">
                <a href="{% url 'purchase:index' %}">SmartShop</a>
            </div>
        </div>



        
        <div class="collapse navbar-collapse" id="topNavBar"> 
            <ul  class="nav navbar-nav">
                <li>
                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" >
                            <span class="small">Shop By</span><br>Category
                            <span class="caret"></span>
                        </button>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'purchase:item' %}#c1">Books</a></li>
                            <li><a href="#">Mobile & Tablets</a></li>
                            <li><a href="{% url 'purchase:item' %}#c3">Computer & Accessories</a></li>
                            <li><a href="#">Home Utensils</a></li>
                            <li><a href="#">Sports, Fitness & Outdoors</a></li>
                            <li><a href="#">Clothing & Accessories</a></li>
                            <li><a href="#">Watches & Eyewears</a></li>
                            <li><a href="{% url 'purchase:item' %}#c8">Shoes</a></li>
                        </ul>
                    </div>
                    
                </li>
                
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="text" class="form-control" name="q" value=""> 
                </div>
                <button class="btn btn-default " type="submit">
                    <span class="glyphicon glyphicon-search"></span>&nbsp;Search
                </button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'purchase:cartdetails' %}">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;Your Cart
                            <span class="badge">{{user.cart_set.count}}</span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button type="button" class="btn btn-default btn-circle dropdown-toggle" data-toggle="dropdown"
                                 style="margin-top:10px;">
                                <i class="glyphicon glyphicon-user"></i>
                            </button>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                            
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'purchase:userprofile' %}">Hello, {{user.username}}</a>
                                <li>
                                <li><a href="{% url 'purchase:cartdetails' %}">
                                    Your Cart <span class="badge">{{user.cart_set.count}}</span></a></li>
                                <li><a href="{% url 'purchase:usersetting' %}">Settings</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'purchase:logout' %}">Log Out</a></li>
                            </ul>
                        </div>
                    
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'purchase:register' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Sign-Up
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'purchase:login' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Sign-In
                        </a>
                    </li>
                {% endif %}
                
             </ul>
        </div>

        
    </div>
</nav>


{% block body %}
{% endblock %}


<br><br><br><br><br><br><br><br>
<footer class="navbar-default">
			<div class="container">
				<div class="row bottom rule">
					

					<div class="col-sm-4 footer-section">
						<strong>Connect with SmartShop</strong>
					    <p>Email promotions, news, and information</p>
					    <form class="form-inline">
					        <div class="form-group">
					            <label 
					                class="sr-only" 
					                for="inputEmail"
					            >Email</label>
					            <input
					                type="email"
					                class="form-control"
					                id="inputEmail"
					                placeholder="address@example.com"
					            >
					         </div>
					         <button type="submit" class="btn btn-default">Subscribe</button>
					     </form>
					</div>

					<div class="col-sm-5 footer-section">
					    <ul class="list-inline">
					        <li class="text-uppercase">Customer Service:</li>
					        <li><a href="#">Returns</a></li>
					        <li><a href="#">Privacy Policy</a></li>
					        <li><a href="#">Our Guarantee</a></li>
					        <li><a href="#">Shipping</a></li>
					        <li><a href="#">Product Guides</a></li>
					        <li><a href="#">Customer Care</a></li>
					    </ul>
					    <ul class="list-inline">
					        <li class="text-uppercase">Social Media &amp; Articles:</li>
					        <li><a href="#">Instagram</a></li>
					        <li><a href="#">Pinterest</a></li>
					        <li><a href="#">Twitter</a></li>
					        <li><a href="#">Facebook</a></li>
					        <li><a href="#">The Best Journal</a></li>
					    </ul>
					    <ul class="list-inline">
					        <li class="text-uppercase">Events:</li>
					        <li><a href="#">Hangout April 30</a></li>
					        <li><a href="#">Makers Faire</a></li>
					    </ul>
					</div>

					<div class="col-sm-3">
					    <address>
					        <strong>SmartShop</strong><br>
					        1000 Some Fantastic Place<br>
					        San Francisco, CA 94103<br>
					        (123) 456-7890 (phone &amp; text)<br>
					        <a href="#">Contact Us</a>
					    </address>
					</div>


				</div>

				<div class="row bottom-rule">
				    <div class="col-sm-12 ">
				        <nav class="navbar navbar-default navbar-footer">
				            <ul class="nav navbar-nav">
				                <li><a href="#">Customer Care</a></li>
				                <li><a href="#">Summer Lookbook</a></li>
				                <li><a href="#">Gift Cards</a></li>
				                <li><a href="#">About SmartShop</a></li>
				                <li><a href="#">Careers</a></li>
				                <li><a href="#">Contact Us</a></li>
				                <li><a href="#">The Best Journal</a></li>
				            </ul>
				        </nav>
				    </div>

				    <div class="row leg-room">
					    <div class="col-md-12 text-center">
					        <h1 class="text-uppercase">SmartShop</h1>
					        <p class="monospaced">
					            &copy;2016 SmartShop Company Inc. 
					            <span class="text-uppercase">All Rights Reserved</span></p>
					    </div>
					</div>
				</div>
				
			</div>
		</footer>


</body>
</html>

purchase/templates/purchase/cartdetails.html
{% extends 'purchase/base.html' %}
{% block title %}Welcome to Your Cart{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="page-header">
        <h3 style="color:darkred; font-size:40px">Welcome to Your Cart, {{user.username}}</h3>
        <h4 style="color:chartreuse">Items in your cart&nbsp;&nbsp;&nbsp;
            <span class="glyphicon glyphicon-menu-down"></span>
        </h4>
    </div> 
    <div class="list-group">

        {% for item in user.cart_set.all %}

        <div class="list-group-item col-md-8">
            <div class="row">
                <div class="col-md-1">
                <img src="../{{ item.product.logo }}" alt="Logo" style="height:90px;width:80px">
                </div>
                <div class="col-md-3 col-md-offset-1">
                    <h4>Product Name:</h4>
                    <p>{{item.product.name}}</p>
                </div> 
                <div class="col-md-2 ">
                    <h4>Price:</h4>
                    <p>${{item.product.price}}</p>
                </div> 
                <div class="col-md-3 col-md-offset-1">
                    <h4>Date Added:</h4>
                    <p>{{item.add_date.date}}</p>
                </div>
                <div class="col-md-1">
                    <br>
                    <a href="{% url 'purchase:deleteitem' item.product_id %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </div>
            </div>
        </div>

        <br>
        {% endfor %}

    </div>

    {% if user.cart_set.all %}
    <div class="col-md-6 col-md-offset-4">
         <br> <br>
        <div class="col-md-3">
            <a href="{% url 'purchase:emptycart' %}">
                <button>Empty Cart</button>
            </a>
        </div>
        <div class="col-md-3">
            <a href="{% url 'purchase:order' %}">
                <button>Place Order</button>
            </a>
        </div>
    </div>
    {% else %}
    <div class="container-fluid">
        <p>Oops ! No item in your Cart.</p><br>
        <p>Click thi <a href="{% url 'purchase:item' %}">Link</a> to begin your shopping</p>        
    </div>
    {% endif %}

</div>

{% endblock %}

purchase/templates/purchase/details.html
{% extends 'purchase/base.html' %}
{% block title %}Welcome to SmartShop{% endblock %}

{% block body %}

<section>
    <div class="container"> 
        <div class="col-md-3">
    
        <img src="../{{ item.logo }}" alt="Logo" style="height:400px;width:260px;">
        </div>
        <div class="col-md-6">
            <p>Category : {{item.category}} </p>
            <p> Product Name : {{item.name}} </p>
            <p> Price : {{item.price}} </p>
        </div>
    </div>

</section>
<br><br><br>

{% endblock %}

purchase/templates/purchase/form_template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-md-offset-4 col-md-10">
            <span class="txt-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-md-3">{{field.label_tag}}</label>
        <div class="col-md-10  ">{{field}}</div>
    </div>
    
{% endfor %}

purchase/templates/purchase/item.html
{% extends 'purchase/base.html' %}
{% block title %}Welcome to SmartShop{% endblock %}

{% block script %}
<script>
    function changeIcon(){
        document.getElementById("icon").classList.remove = "glyphicon glyphicon-star-empty";
        document.getElementById("icon").classList.add = "glyphicon glyphicon-star";
    }
</script>
{% endblock %}
{% block body %}
<section class="container" id="c1">
    <div class="page-header">
        <h2 style="color:darkred; font-size:50px;">Books :</h2>
    </div><br>
    {% for item in category.x1.item_set.all %}
        <div class="col-md-4">
            <figure>
                <a href="{% url 'purchase:details' item.id %}">
                    <img src="{{ item.logo }}" alt="Logo" style="height:400px;width:300px;" class="img-responsive">
                </a>
                 <figcaption class="thumbnail" style="width:300px;">
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:add' item.id %}">
                        <span class="glyphicon glyphicon-shopping-cart " style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:like' item.id %}">
                        <span class="glyphicon glyphicon-thumbs-up" style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:favorite' item.id %}">
                        <span class="glyphicon glyphicon-star-empty" style="font-size:30px; "></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                    <a href="">
                        <span style="font-size:20px">Quic-Details</span>
                    </a>                     
                </figcaption>
                
            </figure>
            
            
        </div>
    {% endfor %}
</section>


<section class="container" id="c3">
    <div class="page-header">
        <h2 style="color:darkred; font-size:50px;">Computers & Accessories :</h2>
    </div><br>
    {% for item in category.x3.item_set.all %}
        <div class="col-md-4">
            <figure>
                <a href="{% url 'purchase:details' item.id %}">
                    <img src="{{ item.logo }}" alt="Logo" style="height:400px;width:300px;" class="img-responsive">
                </a>
                 <figcaption class="thumbnail" style="width:300px;">
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:add' item.id %}">
                        <span class="glyphicon glyphicon-shopping-cart " style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:like' item.id %}">
                        <span class="glyphicon glyphicon-thumbs-up" style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:favorite' item.id %}">
                        <span class="glyphicon glyphicon-star-empty" style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                    <a href="">
                        <span style="font-size:20px">Quick-Details</span>
                    </a>                     
                </figcaption>
                
            </figure>
            
            
        </div>
    {% endfor %}
</section>


<section class="container" id="c8">
    <div class="page-header">
        <h2 style="color:darkred; font-size:50px;">Shoes :</h2>
    </div><br>
    {% for item in category.x8.item_set.all %}
        <div class="col-md-4">
            <figure>
                <a href="{% url 'purchase:details' item.id %}">
                    <img src="{{ item.logo }}" alt="Logo" style="height:400px;width:300px;" class="img-responsive">
                </a>
                 <figcaption class="thumbnail" style="width:300px;">
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:add' item.id %}">
                        <span class="glyphicon glyphicon-shopping-cart " style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:like' item.id %}">
                        <span class="glyphicon glyphicon-thumbs-up" style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                     <a href="{% url 'purchase:favorite' item.id %}">
                        <span class="glyphicon glyphicon-star-empty" style="font-size:30px;"></span>
                     </a>
                     &nbsp;&nbsp;&nbsp;
                    <a href="">
                        <span style="font-size:20px">Quic-Details</span>
                    </a>                     
                </figcaption>
                
            </figure>
            
            
        </div>
    {% endfor %}
</section>

{% endblock %}

purchase/templates/purchase/login.html
{% extends 'purchase/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
 

            
            <div class="col-md-6">
                <div class="panel panle-default">



                    <div class="panel-body">
                        <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'purchase/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>



                </div>
            </div>
            


        </div>
    </div>

{% endblock %}

purchase/templates/purchase/order.html
{% extends 'purchase/base.html' %}
{% block title %}Order Summary{% endblock %}

{% block body %}

	<div class="row col-md-12">
		<div class="col-md-4 ">
			<div class="page-header">
				<h3 style="font-family: cursive; color: maroon;">Order Details</h3>
			</div>

			<div>
				<ul class="list-group">
					{% for item in user.cart_set.all %}
						<li class="list-group-item">{{ item.product.name }}</li>
					{% endfor %}
				</ul>
			</div>			

		</div>

		<div class="col-md-4">

			<div class="page-header">
				<h3 style="font-family: cursive; color: maroon;">User Details</h3>
			</div>

			{% if user.userdetails_set.all %}
			<ul class="list-group">
				{% for detail in user.userdetails_set.all %}
					<li class="list-group-item">{{detail.address}}</li>
					<li class="list-group-item">{{detail.phone_number}}</li>
				{% endfor %}
			</ul>
			{% else %}
				{% include 'purchase/form_template.html' %}
			{% endif %}

		</div>

		<div class="col-md-4">
			<div class="page-header">
				<h3 style="font-family: cursive; color: maroon;">Payment Method</h3>
			</div>

			<ul class="list-group">
				<li class="list-group-item">Cash On Delivery</li>
				<li class="list-group-item">Debit/Maestro Cart</li>
				<li class="list-group-item">Online/Net banking</li>
			</ul>
		</div>

	</div>


	<div class="col-md-4 col-md-offset-6">
		<br><br>
		<button class="btn btn-primary">
				Review Cart
		</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<button class="btn btn-primary">
				Confirm Order
		</button>
	</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
{% endblock %}